#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw


def ensure_names(raw: str) -> list[str]:
    names = [item.strip() for item in raw.split(",") if item.strip()]
    if len(names) != 9:
        raise SystemExit("--names must contain exactly 9 comma-separated icon names")
    return names


def cell_box(width: int, height: int, index: int) -> tuple[int, int, int, int]:
    col = index % 3
    row = index // 3
    x0 = round(col * width / 3)
    x1 = round((col + 1) * width / 3)
    y0 = round(row * height / 3)
    y1 = round((row + 1) * height / 3)
    return x0, y0, x1, y1


def rectangles_from_mask(image: Image.Image, threshold: int) -> list[tuple[int, int, int, int]]:
    mask = image.convert("L")
    pixels = mask.load()
    width, height = mask.size
    active: dict[tuple[int, int], tuple[int, int, int]] = {}
    rects: list[tuple[int, int, int, int]] = []

    for y in range(height):
        spans: list[tuple[int, int]] = []
        x = 0
        while x < width:
            while x < width and pixels[x, y] >= threshold:
                x += 1
            if x >= width:
                break
            x0 = x
            while x < width and pixels[x, y] < threshold:
                x += 1
            spans.append((x0, x))

        next_active: dict[tuple[int, int], tuple[int, int, int]] = {}
        for span in spans:
            if span in active:
                next_active[span] = active.pop(span)
            else:
                x0, x1 = span
                next_active[span] = (x0, x1, y)

        for x0, x1, y0 in active.values():
            rects.append((x0, y0, x1, y))
        active = next_active

    for x0, x1, y0 in active.values():
        rects.append((x0, y0, x1, height))
    return rects


def rects_to_path(rects: list[tuple[int, int, int, int]]) -> str:
    return "".join(f"M{x0} {y0}H{x1}V{y1}H{x0}Z" for x0, y0, x1, y1 in rects)


def ink_bbox(image: Image.Image, threshold: int) -> tuple[int, int, int, int]:
    mask = image.convert("L")
    pixels = mask.load()
    width, height = mask.size
    xs: list[int] = []
    ys: list[int] = []
    for y in range(height):
        for x in range(width):
            if pixels[x, y] < threshold:
                xs.append(x)
                ys.append(y)
    if not xs:
        return 0, 0, width, height
    return min(xs), min(ys), max(xs) + 1, max(ys) + 1


def cropped_view_box(
    bbox: tuple[int, int, int, int], size: tuple[int, int], padding_ratio: float
) -> tuple[int, int, int, int]:
    x0, y0, x1, y1 = bbox
    width, height = size
    ink_width = x1 - x0
    ink_height = y1 - y0
    padding = round(max(ink_width, ink_height) * padding_ratio)
    vx = max(0, x0 - padding)
    vy = max(0, y0 - padding)
    x2 = min(width, x1 + padding)
    y2 = min(height, y1 + padding)
    return vx, vy, x2 - vx, y2 - vy


def format_view_box(box: tuple[int, int, int, int]) -> str:
    x, y, width, height = box
    return f"{x} {y} {width} {height}"


def draw_rects(size: tuple[int, int], rects: list[tuple[int, int, int, int]]) -> Image.Image:
    image = Image.new("RGBA", size, (255, 255, 255, 255))
    draw = ImageDraw.Draw(image)
    for rect in rects:
        x0, y0, x1, y1 = rect
        draw.rectangle((x0, y0, x1 - 1, y1 - 1), fill=(0, 0, 0, 255))
    return image


def compare_images(expected: Image.Image, actual: Image.Image, diff_path: Path) -> dict:
    exp = expected.convert("RGBA")
    act = actual.convert("RGBA")
    if exp.size != act.size:
        act = act.resize(exp.size, Image.Resampling.NEAREST)
    diff = ImageChops.difference(exp, act)
    diff_path.parent.mkdir(parents=True, exist_ok=True)
    diff.save(diff_path)
    changed = 0
    for r, g, b, a in diff.getdata():
        if (r + g + b + a) / 4 > 12:
            changed += 1
    total = exp.width * exp.height
    return {
        "diffPixels": changed,
        "totalPixels": total,
        "diffRatio": round(changed / total, 6),
        "pass": changed / total <= 0.05,
    }


def svg_body(path_data: str) -> str:
    return f'<path fill="currentColor" stroke="none" fill-rule="evenodd" d="{path_data}"></path>'


def write_svg(path: Path, width: int, height: int, body: str) -> None:
    path.write_text(
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}">'
            f"{body}</svg>\n"
        ),
        encoding="utf-8",
    )


def write_js(path: Path, icons: list[dict]) -> None:
    lines = [
        "/* Generated by scripts/icon_svg_replica.py. Do not edit by hand. */",
        "window.ICON_REPLICA_LIBRARY = {",
    ]
    for item in icons:
        lines.append(
            f'  {json.dumps(item["name"])}: {{ viewBox: {json.dumps(item["viewBox"])}, '
            f'body: `{item["body"]}` }},'
        )
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def replicate(args: argparse.Namespace) -> None:
    names = ensure_names(args.names)
    out = Path(args.out)
    target_dir = out / "targets"
    enlarged_dir = out / "enlarged-3x"
    replica_dir = out / "replica-png"
    svg_dir = out / "svg"
    diff_dir = out / "diff"
    for directory in [target_dir, enlarged_dir, replica_dir, svg_dir, diff_dir]:
        directory.mkdir(parents=True, exist_ok=True)

    generated_icons = []
    manifest = []
    with Image.open(args.input).convert("RGBA") as board:
        for index, name in enumerate(names):
            filename = f"{index + 1:02d}-{name}"
            cell = board.crop(cell_box(board.width, board.height, index))
            target_path = target_dir / f"{filename}.png"
            enlarged_path = enlarged_dir / f"{filename}@3x.png"
            replica_path = replica_dir / f"{filename}.png"
            svg_path = svg_dir / f"{filename}.svg"
            diff_path = diff_dir / f"{filename}.png"

            cell.save(target_path)
            cell.resize((cell.width * 3, cell.height * 3), Image.Resampling.NEAREST).save(enlarged_path)

            rects = rectangles_from_mask(cell, args.threshold)
            path_data = rects_to_path(rects)
            body = svg_body(path_data)
            bbox = ink_bbox(cell, args.threshold)
            view_box = cropped_view_box(bbox, cell.size, args.padding_ratio)
            replica = draw_rects(cell.size, rects)
            replica.save(replica_path)
            write_svg(svg_path, cell.width, cell.height, body)
            result = compare_images(cell, replica, diff_path)

            generated_icons.append(
                {
                    "name": name,
                    "viewBox": format_view_box(view_box),
                    "body": body,
                }
            )
            manifest.append(
                {
                    "name": name,
                    "target": str(target_path),
                    "enlarged": str(enlarged_path),
                    "replicaPng": str(replica_path),
                    "svg": str(svg_path),
                    "diff": str(diff_path),
                    "inkBBox": bbox,
                    "displayViewBox": view_box,
                    "rectangles": len(rects),
                    "pathLength": len(path_data),
                    **result,
                }
            )

    write_js(out / "icon-replicas-board-01.js", generated_icons)
    summary = {
        "source": str(args.input),
        "out": str(out),
        "threshold": args.threshold,
        "cropPaddingRatio": args.padding_ratio,
        "diffThreshold": 0.05,
        "pass": all(item["pass"] for item in manifest),
        "maxDiffRatio": max(item["diffRatio"] for item in manifest),
        "icons": manifest,
    }
    (out / "manifest.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"pass": summary["pass"], "maxDiffRatio": summary["maxDiffRatio"]}, ensure_ascii=False, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description="Create enlarged single-icon references and currentColor SVG replicas.")
    parser.add_argument("--input", required=True, help="Path to the cleaned 3x3 icon board.")
    parser.add_argument("--out", required=True, help="Output directory.")
    parser.add_argument("--names", required=True, help="Exactly 9 comma-separated icon names in reading order.")
    parser.add_argument("--threshold", type=int, default=128, help="Pixel luminance threshold for ink extraction.")
    parser.add_argument(
        "--padding-ratio",
        type=float,
        default=0.06,
        help="Padding added around the ink bounding box before the page display viewBox is written.",
    )
    parser.set_defaults(func=replicate)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
